### ISSUE TITLE
Dark theme screen flickers when clicking through routes

### ISSUE THREAD

**Issue by dvzrd** [drehimself/gridsome-portfolio-starter#120]
Hello!

I've noticed an issue on the dark theme when clicking through different routes. During the page transition, the background flickers back to the light theme for a second - this gives off a pretty strange effect that's not present in the light theme.

I'm guessing the theme resets the theme when it loads a new page but not really sure yet.

Also, really awesome starter! I'm having a great time trying out Gridsome with it. Thanks!

**Comment by dvzrd** [comment]
There's a simple fix for this using CSS - by adding a dark theme `background-color` to the `header, main, and footer` wrappers inside the layout.

I added something like this to `main.css`:

```
.content-wrapper > .header,
.content-wrapper > .page,
.content-wrapper > .footer {
  background-color: var(--bg-background-primary);
}
```

Your layout markup would have to be updated to something like this for the above to work:

```
<header class="header ..."></header>
<main class="page"></main>
<footer class="footer"></header>
```

Or you can also do something like this with the existing layout markup (I wouldn't recommend doing this because the selectors can cause bugs in the future):

```
.content-wrapper > header
.content-wrapper > div.flex-grow
.content-wrapper > footer
```

---

There's also the option of removing (but then you lose the transition effect):

```
.content-wrapper {
  transition: background-color .25s;
}
```

---

But maybe there's a way to fix this using a calculated class or method in the theme switcher or layout or something. Not sure, haven't really tried that yet (still learning about vue).

Let me know if you want me to push some of these style updates or feel free to do it yourself if you like them. Cheers!

**Comment by drehimself** [comment]
Hey there! Thanks for looking into this.

Sure, I'll accept PRs if it doesn't break anything else 🙃

**Comment by dvzrd** [comment]
> Hey there! Thanks for looking into this.
> 
> Sure, I'll accept PRs if it doesn't break anything else 🙃

Cool, I'll try to get a PR up over the weekend whenever I have some free time.
