### ISSUE TITLE
Filtering blog list

### ISSUE THREAD

**Issue by findborg** [drehimself/gridsome-portfolio-starter#153]
So,  I am trying to build a text input to filter the blog list.  I tried writing a computed function but I keep getting errors.  I was wondering if you could give me some insight?

**Comment by findborg** [comment]
I would like for the filter to look thru the title, date, summary,  at the very least.

**Comment by drehimself** [comment]
Sorry, this is specific to your project and not much info has been provided. Hopefully you've figured it out by now.
