### ISSUE TITLE
Trailing slash question (blog)

### ISSUE THREAD

**Issue by SherG** [drehimself/gridsome-portfolio-starter#16]
Great template! Thank you for your work on this Andre.

My question is: Google Page Speed Insights suggests "Avoid multiple page redirects
Potential savings of 780 ms" - Redirects introduce additional delays before the page can be loaded."

I'm not clear why GPI is "seeing" a redirect on each blog page.  I noticed that blog pages load without the trailing slash in Chrome, but if you hit the refresh button, Chrome adds a trailing slash. (I haven't seen this behavior in Chrome on on other sites without trailing slashes, like: 
https://daringfireball.net/projects/markdown/syntax )

Any input would be appreciated. Thanks!

**Comment by drehimself** [comment]
Hmm, I honestly don't know what the difference is with or without a trailing slash. If you want to be consistent, you can just add a trailing slash wherever I'm linking to the blog page or blog posts using `<g-link>`. No idea if that will help with the score on GPI.

If it does, let me know and I'll add it in. Or if you find any other tweaks that can increase the GPI score 🙂
