### ISSUE TITLE
Search doesn't work if pathPrefix is used

### ISSUE THREAD

**Issue by shreyasnagare** [drehimself/gridsome-portfolio-starter#17]
The search wouldn't work if this website isn't served on the root of a domain (example: [deployed to GitHub pages](https://gridsome.org/docs/deploy-to-github/#deploy-to-github-pages)) as [the axios request](https://github.com/drehimself/gridsome-portfolio-starter/blob/e8930984f20f50e9a79542139ca07c47d00211f7/src/components/SearchInput.vue#L67) doesn't take [pathPrefix](https://gridsome.org/docs/config/#pathprefix) into consideration.

**Comment by drehimself** [comment]
Any idea on how to fix this? I'm trying to import the `pathPrefix` from the gridsome.config.js but I can't seem to get it working.

PRs accepted!
