### ISSUE TITLE
how to have blog as main page?

### ISSUE THREAD

**Issue by lorvent** [drehimself/gridsome-portfolio-starter#29]
Hello,
i want to use it as only blog site and i don't need an index page,
instead blog page will become index.

can you tell me how to do that?

thanks.

**Comment by drehimself** [comment]
In `/src/pages` you just have to replace `Index.vue` with `Blog.vue`. There are also a few minor changes to get pagination to work. I created a branch for you here: https://github.com/drehimself/gridsome-portfolio-starter/tree/blog-only.

**Comment by lorvent** [comment]
WOWWW... so nice of you!

after spending months on move away from wp and embrace static site generators....i found yours and https://gridsome-starter-bootstrap.loke.dev/ are the best ones to go ahead.

thanks for that branch.
