### ISSUE TITLE
Manipulating post URLs

### ISSUE THREAD

**Issue by SahilMaharaj** [drehimself/gridsome-portfolio-starter#60]
Hey Andre,

I noticed in your blog posts (.md files) that the file names begin with the date, however, the URL rendered in the browser does not contain the date. I see that you specified a path in the frontmatter of posts to set a custom URL, but how did you get this to work correctly without getting a 404?

Thanks!

**Comment by lorvent** [comment]
were you able to modif post URLs? @SahilMaharaj

**Comment by SahilMaharaj** [comment]
Yes I was. Thanks for following up. Was super simple. :)

**Comment by lorvent** [comment]
i wanted to have something like URL/tag/slug

is that possible?

**Comment by SahilMaharaj** [comment]
Yeah it is. I haven't messed around with tags too much but it's pretty
straight forward to setup from.whay I remember. Check out Like Diebolds
video on YouTube where he sets up tags. You'll need to setup a tag template
as well.
