### ISSUE TITLE
are you planning to add any headless CMS?

### ISSUE THREAD

**Issue by lorvent** [drehimself/gridsome-portfolio-starter#65]
Hello,
Are you planning to add any headless CMS like strapi / netlify-cms.

thanks.

---
i am so impressed with the concept of fast loading and static sites and netlify
so if a cms is available, i can use it in place of wordpress for client sites.

thanks.

**Comment by drehimself** [comment]
Not on this repo as it's just an example for others to learn from or fork if they want to use it.

If you are interested, I have a video on using Gridsome with Netlify CMS: https://www.youtube.com/watch?v=ryP1RMA7P9Y
