### ISSUE TITLE
Use markdown for all content

### ISSUE THREAD

**Issue by mrcasablr** [drehimself/gridsome-portfolio-starter#66]
Currently, the index page has content embedded in index.vue file. Instead, just like blog content, separating content into a markdown will keep content and presentation separate.

This makes it easy for users using this starter easy to get started by only modifying the markdown files and CSS.

**Comment by drehimself** [comment]
Thanks for the suggestion.

You are free to fork this repo and modify it so the index page uses markdown.

I'm going to leave it this way as I think it is simpler to get started.
