### ISSUE TITLE
Errors / Warning when building (found solution)

### ISSUE THREAD

**Issue by natedalliard** [drehimself/gridsome-portfolio-starter#7]
I got a lot of these when building:
````
(node:3018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
````

I solved it by adding a `.catch()` where the axios call is for the search [here](https://github.com/drehimself/gridsome-portfolio-starter/blob/master/src/components/SearchInput.vue#L69). I just `console.log(error)`. Not sure if that is the best "solution".

The theme is still building so nothing is really "broken" here. Just wanted to let you know.

**Comment by drehimself** [comment]
Hmm, where are you seeing this warning? Is it when you do `gridsome build`? I'm not seeing it. Could it be a setting in node?

Anyways, probably a good idea to catch an error on the axios call. I'm ok with `console.log`-ing the error. Happy to accept a PR!

**Comment by natedalliard** [comment]
Here we go: #8.

Possible. I am running `yarn 1.16` and `nodejs-11.14`.
