### ISSUE TITLE
Syntax highlighting not working with Shiki

### ISSUE THREAD

**Issue by peoray** [drehimself/gridsome-portfolio-starter#70]
I don't know but my code syntax highlighting isn't working in my markdown files. When I inspected the element, I observed that the styles defined in markdown CSS is what gets applied. Please, how do I ensure that Shiki styles get applied for syntax highlighting?

Here is the link to my [repo](https://github.com/peoray/peoray.dev/) and the live [link](https://peoray-blog.netlify.com/blog/display-password-form-input) of a blog article with syntax highlighting. I'd appreciate any help

Thanks for the wonderful theme, saved me a lot of time :)

**Comment by drehimself** [comment]
Your gridsome config for remark plugins is being overwritten. Try commenting out the lines below and you'll see the syntax highlighting working.

https://github.com/peoray/peoray.dev/blob/master/gridsome.config.js#L55-L62
