### ISSUE TITLE
better slugs for tags

### ISSUE THREAD

**Issue by lorvent** [drehimself/gridsome-portfolio-starter#71]
Hello,
Currently if we have a tag say `hello world`, in url it creates `hello%20world`, is it possible to get it something like `hello-world` ?

thanks.

**Comment by drehimself** [comment]
Not sure how to do this, from my (limited) understanding the tag url is generated from the name of it. If you want a dash, you're going to have to add it manually in the tag name. If you know how to automatically slugify it, I'm open to PRs.
