### ISSUE TITLE
Syntax highlighting does not work in production

### ISSUE THREAD

**Issue by peoray** [drehimself/gridsome-portfolio-starter#73]
I'm trying to use this [plugin](https://github.com/DavidCouronne/gridsome-plugin-remark-prismjs-all) for syntax highlighting. 
While it works on development, it doesn't work when the site is live. I don't know if I'm doing something wrong as regards the theme or if the issue is from the plugin itself. Not sure which it is. 

Here is my [repo](https://github.com/peoray/peoray.dev/) and here is a smaple live site blog [article](https://www.peoray.com/blog/display-password-form-input)

**Comment by drehimself** [comment]
It's related to purgecss. I looked briefly and tried adding some classes to the whitelist array in `purgecss.config.js`. It didn't work completely, but it's a start. You can also remove purgecss completely if you want, but then your css file will be huge. Good luck!

**Comment by peoray** [comment]
In the case of the whitelist, the tags I can see are HTML elements or Gridsome components name, how do you add a class to the list?
