### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by BrianMwas** [drehimself/gridsome-portfolio-starter#80]
Routing using the search bar is not working there seems to be a drag when navigating

**Comment by BrianMwas** [comment]
You can go to briandev.netlify.com to see what am saying..

**Comment by BrianMwas** [comment]
Mostly using the phone

**Comment by drehimself** [comment]
I'm not sure I understand correctly. Can you elaborate?

**Comment by BrianMwas** [comment]
Sorry, head on over to briandev.neltify.com and try navigating to a
particular blog using the search bar you will realize it doesn't
navigate or the blog link it does not navigate either to the blog page or
search link

**Comment by drehimself** [comment]
This is your own codebase forked from this repo. I don't know what changes you introduced but there's an issue with routing as you said. It doesn't happen on the demo project so I'm not sure.
