### ISSUE TITLE
Absolute URL for blog post path

### ISSUE THREAD

**Issue by jhsu98** [drehimself/gridsome-portfolio-starter#81]
I'm trying to use an absolute URL for the path in one of my blogs, but I get the following error 
```
Error: child "path" fails because ["path" with value "https://medium.com" fails to match the leading slash pattern]
```

I figure there's some sort of data validation for the frontmatter path property but I don't know where to change that.

**Comment by drehimself** [comment]
Hey there. I'm able to reproduce this but I have no idea how to fix it, sorry! Maybe ask on the gridsome repo? A really shitty workaround would be just to create an actual post locally then have the content of that post link to your medium post 😅

**Comment by jhsu98** [comment]
Haha I've been doing exactly that (making an actual post with a link). I'll ask around and if I figure it out I'll circle back and post here too.
