### ISSUE TITLE
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by jbint** [drehimself/gridsome-portfolio-starter#91]
Hi, there, thanks so much for this starter. I'm getting a build error on the sitemap plugin and cannot pinpoint a fix. It will build successfully when I remove the plugin from my gridsome.config.js file, but when I add it back in, I get this error. 

I haven't found a solution pertaining to Gridsome on this error. Just React. 

Any suggestions on how to troubleshoot this would be greatly appreciated. 

Thanks so much and thank you again for putting this together. It's been really great for me to learn. Thanks.

`Gridsome v0.6.9

Initializing plugins...
Initialize - 1.67s
Load sources - 0.14s
Create GraphQL schema - 0.36s
Create pages and templates - 0.16s
Generate code - 0.1s
Bootstrap finish - 2.44s
Execute GraphQL (5 queries) - 1.67s
Write page data (6 files) - 0.07s
Compile assets - 40.09s
Render HTML (13 files) - 0.79s
Process files (0 files) - 0s
Process images (18 images) - 2.77s
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at api.afterBuild (C:\Users\Admin\code\gridsome-portfolio-starter\node_modules\@gridsome\plugin-sitemap\index.js:21:27)
    at Events.dispatch (C:\Users\Admin\code\gridsome-portfolio-starter\node_modules\gridsome\lib\app\Events.js:24:17)`

**Comment by drehimself** [comment]
Did an update, all should be good now!

**Comment by jbint** [comment]
Awesome, thank you! And thanks again for your starter.
