### ISSUE TITLE
npm audit :   35 vulnerabilities require manual review. See the full report for details.

### ISSUE THREAD

**Issue by nlebellier** [drehimself/gridsome-portfolio-starter#92]
First of all thanks to share your work which helps me to start with gridsome right now !
But what do you think about security issues ? Is it important or not ?
```
found 36 vulnerabilities (26 low, 1 moderate, 9 high) in 23573 scanned packages
  run `npm audit fix` to fix 1 of them.
  35 vulnerabilities require manual review. See the full report for details.
```
What do you think about that ?

**Comment by drehimself** [comment]
For me personally, no, since this is just a demo project.
